export const gitaQuotes = {
  inspired: [
    { text: "You have the right to perform your prescribed duty, but you are not entitled to the fruits of action.", reference: "Bhagavad Gita 2.47" },
    { text: "Through selfless service, you will always be fruitful and find the fulfillment of your desires.", reference: "Bhagavad Gita 3.10" },
    { text: "Whatever action a great man performs, common men follow.", reference: "Bhagavad Gita 3.21" },
    { text: "Do your work with the welfare of others always in mind.", reference: "Bhagavad Gita 3.25" },
    { text: "Strive constantly to serve the welfare of the world.", reference: "Bhagavad Gita 3.19" },
    { text: "A person can rise through the efforts of his own mind; or draw himself down, in the same manner.", reference: "Bhagavad Gita 6.5" },
    { text: "One who performs his duty without attachment, surrendering the results unto the Supreme Lord, is unaffected by sinful action, as the lotus leaf is untouched by water.", reference: "Bhagavad Gita 5.10" },
    { text: "There is nothing lost or wasted in this life.", reference: "Bhagavad Gita 2.40" },
    { text: "The embodied soul is eternal in existence, indestructible, and infinite.", reference: "Bhagavad Gita 2.18" },
    { text: "We are kept from our goal not by obstacles, but by a clear path to a lesser goal.", reference: "Inspired by Gita Principles" },
    { text: "No one who does good work will ever come to a bad end, either here or in the world to come.", reference: "Bhagavad Gita 6.40" },
    { text: "Man is made by his belief. As he believes, so he is.", reference: "Bhagavad Gita 17.3" },
    { text: "Seek refuge in the attitude of detachment and you will amass the wealth of spiritual awareness.", reference: "Bhagavad Gita 2.49" },
    { text: "One who sees inaction in action, and action in inaction, is intelligent among men.", reference: "Bhagavad Gita 4.18" },
    { text: "Arise, slay thy enemies, enjoy a prosperous kingdom.", reference: "Bhagavad Gita 11.33" }
  ],
  focused: [
    { text: "For the uncontrolled, there is no wisdom, nor for the uncontrolled is there the power of concentration.", reference: "Bhagavad Gita 2.66" },
    { text: "When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.", reference: "Bhagavad Gita 6.19" },
    { text: "Those who are motivated only by desire for the fruits of action are miserable, for they are constantly anxious about the results of what they do.", reference: "Bhagavad Gita 2.49" },
    { text: "Perform your duty equipoised, O Arjuna, abandoning all attachment to success or failure. Such equanimity is called yoga.", reference: "Bhagavad Gita 2.48" },
    { text: "The mind acts like an enemy for those who do not control it.", reference: "Bhagavad Gita 6.6" },
    { text: "Reshape yourself through the power of your will.", reference: "Bhagavad Gita 6.5" },
    { text: "Let a man lift himself by his own self alone; let him not lower himself.", reference: "Bhagavad Gita 6.5" },
    { text: "He whose mind is untroubled in the midst of sorrows and is free from eager desire amid pleasures, he is a sage of steady wisdom.", reference: "Bhagavad Gita 2.56" },
    { text: "Action is greater than inaction. Perform therefore thy task in life.", reference: "Bhagavad Gita 3.8" },
    { text: "But it is by the constant practice of detachment that the mind is controlled.", reference: "Bhagavad Gita 6.35" },
    { text: "When a man dwells on the pleasure of sense, attraction for them arises in him.", reference: "Bhagavad Gita 2.62" },
    { text: "As a strong wind sweeps away a boat on the water, even one of the roaming senses on which the mind focuses can carry away a man's intelligence.", reference: "Bhagavad Gita 2.67" },
    { text: "Therefore, without being attached to the fruits of activities, one should act as a matter of duty.", reference: "Bhagavad Gita 3.19" },
    { text: "The disciplined mind brings peace.", reference: "Bhagavad Gita 2.64" },
    { text: "From anger, complete delusion arises, and from delusion bewilderment of memory.", reference: "Bhagavad Gita 2.63" }
  ],
  overwhelmed: [
    { text: "Peace is found in surrendering the illusion of control.", reference: "Bhagavad Gita 18.66" },
    { text: "For him who has conquered the mind, the mind is the best of friends.", reference: "Bhagavad Gita 6.6" },
    { text: "He who has let go of hatred, who treats all beings with kindness and compassion... that devotee of mine is very dear to me.", reference: "Bhagavad Gita 12.13" },
    { text: "The peace of God is with them whose mind and soul are in harmony.", reference: "Bhagavad Gita 5.26" },
    { text: "Even a little progress is freedom from fear.", reference: "Bhagavad Gita 2.40" },
    { text: "It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.", reference: "Bhagavad Gita 3.35" },
    { text: "Calmness, gentleness, silence, self-restraint, and purity: these are the disciplines of the mind.", reference: "Bhagavad Gita 17.16" },
    { text: "There is neither this world nor the world beyond nor happiness for the one who doubts.", reference: "Bhagavad Gita 4.40" },
    { text: "O mighty-armed son of Kunti, it is undoubtedly very difficult to curb the restless mind, but it is possible by suitable practice.", reference: "Bhagavad Gita 6.35" },
    { text: "That which seems like poison at first, but tastes like nectar in the end.", reference: "Bhagavad Gita 18.37" },
    { text: "Do not let your heart be troubled.", reference: "Inspired by Gita Principles" },
    { text: "In the dark night of all beings awakes to Light the tranquil man.", reference: "Bhagavad Gita 2.69" },
    { text: "Free from attachment, fear, and anger, fully absorbed in Me.", reference: "Bhagavad Gita 4.10" },
    { text: "Give up claiming ownership, and you shall find true peace.", reference: "Bhagavad Gita 2.71" },
    { text: "He who is not disturbed by happiness and distress and is steady in both is certainly eligible for liberation.", reference: "Bhagavad Gita 2.15" }
  ],
  fatigued: [
    { text: "There is no true peace for the one who does not meditate, and without peace, how can there be happiness?", reference: "Bhagavad Gita 2.66" },
    { text: "Those who eat too much or eat too little, who sleep too much or sleep too little, will not succeed in meditation.", reference: "Bhagavad Gita 6.16" },
    { text: "But the person who is regulated in his habits of eating, sleeping, recreation and work can mitigate all material pains by practicing the yoga system.", reference: "Bhagavad Gita 6.17" },
    { text: "He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains.", reference: "Bhagavad Gita 6.17" },
    { text: "The soul is neither born, and nor does it die.", reference: "Bhagavad Gita 2.20" },
    { text: "The wise grieve neither for the living nor for the dead. Treat your body as a vessel needing restoration.", reference: "Bhagavad Gita 2.11" },
    { text: "Even the wise are confused about what is action and what is inaction. Step back and restore your clarity.", reference: "Bhagavad Gita 4.16" },
    { text: "That happiness which is derived from the contact of the senses with their objects and which appears like nectar at first but poison at the end is of the nature of passion.", reference: "Bhagavad Gita 18.38" },
    { text: "A tranquil mind provides an unshakeable foundation.", reference: "Bhagavad Gita 2.65" },
    { text: "The individual is the passenger in the chariot of the material body, and intelligence is the driver. Take care of the chariot.", reference: "Inspired by Gita Metaphor" },
    { text: "Do not subject yourself to unnecessary austerity that tortures the body.", reference: "Bhagavad Gita 17.6" },
    { text: "When a person is completely engaged in the transcendental loving service of the Lord, he is pleased in himself.", reference: "Bhagavad Gita" },
    { text: "Resting the wandering mind is the key to preserving vital energy.", reference: "Bhagavad Gita 6.26" },
    { text: "He who sees inaction in action, has truly rested.", reference: "Bhagavad Gita 4.18" },
    { text: "Balance your duties, but anchor yourself in peace.", reference: "Bhagavad Gita 5.29" }
  ],
  evaluative: [
    { text: "By true knowledge, the ignorance of the soul is destroyed, and the supreme reality is revealed like the sun shining in the day.", reference: "Bhagavad Gita 5.16" },
    { text: "As a blazing fire turns firewood to ashes, O Arjuna, so does the fire of knowledge burn to ashes all reactions to material activities.", reference: "Bhagavad Gita 4.37" },
    { text: "There is nothing in this world so purifying as knowledge.", reference: "Bhagavad Gita 4.38" },
    { text: "When one's intelligence has emerged from the dense forest of delusion, one becomes indifferent to all that has been heard and all that is to be heard.", reference: "Bhagavad Gita 2.52" },
    { text: "The humble sages, by virtue of true knowledge, see with equal vision a learned and gentle brahman, a cow, an elephant, a dog and a dog-eater.", reference: "Bhagavad Gita 5.18" },
    { text: "A person is considered still further advanced when he regards honest well-wishers, affectionate benefactors, the neutral, mediators, the envious, friends and enemies, the pious and the sinners all with an equal mind.", reference: "Bhagavad Gita 6.9" },
    { text: "One who sees the Supersoul accompanying the individual soul in all bodies, and who understands that neither the soul nor the Supersoul within the destructible body is ever destroyed, actually sees.", reference: "Bhagavad Gita 13.28" },
    { text: "Approach a spiritual master, inquire from him submissively and render service unto him.", reference: "Bhagavad Gita 4.34" },
    { text: "Knowledge is better than mechanical practice.", reference: "Bhagavad Gita 12.12" },
    { text: "Action should culminate in wisdom.", reference: "Bhagavad Gita 4.33" },
    { text: "He perceives the truth who sees all beings as rooted in the One.", reference: "Bhagavad Gita 13.30" },
    { text: "The man of wisdom is never deluded.", reference: "Bhagavad Gita 4.35" },
    { text: "The light of knowledge eradicates the darkness of ignorance.", reference: "Bhagavad Gita 10.11" },
    { text: "An intelligent person does not take part in the sources of misery, which are due to contact with the material senses.", reference: "Bhagavad Gita 5.22" },
    { text: "That knowledge by which one undivided spiritual nature is seen in all living entities, though they are divided into innumerable forms, you should understand to be in the mode of goodness.", reference: "Bhagavad Gita 18.20" }
  ],
  doubt: [
    { text: "One who doubts, neither has peace in this world nor in the next.", reference: "Bhagavad Gita 4.40" },
    { text: "Therefore, with the sword of knowledge, cut to pieces the doubts that have arisen in your heart.", reference: "Bhagavad Gita 4.42" },
    { text: "Whatever you do, make it an offering to me - the food you eat, the sacrifices you make, the help you give, even your suffering.", reference: "Bhagavad Gita 9.27" },
    { text: "Surrender fully unto Him. By His grace you will attain transcendental peace and the supreme and eternal abode.", reference: "Bhagavad Gita 18.62" },
    { text: "Knowledge is covered by this eternal enemy of the wise, in the form of desire, which burns like an unquenchable fire.", reference: "Bhagavad Gita 3.39" },
    { text: "We behold what we are, and we are what we behold.", reference: "Inspired by Gita Teachings" },
    { text: "Faith is the heart's natural gravitation toward its source.", reference: "Bhagavad Gita 17.3" },
    { text: "Abandon all varieties of religion and just surrender unto Me.", reference: "Bhagavad Gita 18.66" },
    { text: "He who has faith, who is endowed with earnestness, and who has subdued his senses, obtains knowledge.", reference: "Bhagavad Gita 4.39" },
    { text: "From wherever the mind wanders due to its flickering and unsteady nature, one must certainly withdraw it.", reference: "Bhagavad Gita 6.26" },
    { text: "Lift yourself out of your doubt, rise and conquer.", reference: "Bhagavad Gita 2.37" },
    { text: "Even if you are considered the most sinful of all sinners, when you are situated in the boat of transcendental knowledge you will be able to cross over the ocean of miseries.", reference: "Bhagavad Gita 4.36" },
    { text: "Therefore, get up and prepare to fight. After conquering your enemies you will enjoy a flourishing kingdom.", reference: "Bhagavad Gita 11.33" },
    { text: "Fear not. What is not real, never was and never will be. What is real, always was and cannot be destroyed.", reference: "Bhagavad Gita 2.16" },
    { text: "He who sees me everywhere and sees everything in me will not be lost to me, nor will I ever be lost to him.", reference: "Bhagavad Gita 6.30" }
  ],
  reflective: [
    { text: "He who is situated in the spiritual reality, who is steady in mind, who neither rejoices upon achieving something pleasant nor laments upon obtaining something unpleasant, is self-realized.", reference: "Bhagavad Gita 5.20" },
    { text: "When a person responds to the joys and sorrows of others as if they were his own, he has attained the highest state of spiritual union.", reference: "Bhagavad Gita 6.32" },
    { text: "One should engage oneself in the practice of yoga with determination and faith and not be deviated from the path.", reference: "Bhagavad Gita 6.24" },
    { text: "A person is said to be established in self-realization and is called a yogi when he is fully satisfied by virtue of acquired knowledge.", reference: "Bhagavad Gita 6.8" },
    { text: "He who has no attachments can really love others, for his love is pure and divine.", reference: "Inspired by Gita Philosophy" },
    { text: "Those whose minds and intelligence are completely focused on Him, their misgivings are completely removed by complete knowledge.", reference: "Bhagavad Gita 5.17" },
    { text: "Look within. The supreme truth of everything is hidden in the quietest depths of your soul.", reference: "Bhagavad Gita 15.15" },
    { text: "He who delights in the self, who is satisfied with the self, and is content in the self alone, for him there is no duty.", reference: "Bhagavad Gita 3.17" },
    { text: "They live in wisdom who see themselves in all and all in them.", reference: "Bhagavad Gita 6.29" },
    { text: "As the waters of the ocean, being completely full and still, are not disturbed by the streams flowing into it; similarly, a person who is not disturbed by the incessant flow of desires can achieve peace.", reference: "Bhagavad Gita 2.70" },
    { text: "To action alone hast thou a right and never at all to its fruits.", reference: "Bhagavad Gita 2.47" },
    { text: "You came empty-handed, and you will leave empty-handed.", reference: "Inspired by Gita Teachings" },
    { text: "The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions.", reference: "Bhagavad Gita" },
    { text: "Out of compassion for them, I, dwelling in their hearts, destroy with the shining lamp of knowledge the darkness born of ignorance.", reference: "Bhagavad Gita 10.11" },
    { text: "The Self is the friend of the self for him who has conquered himself by the Self.", reference: "Bhagavad Gita 6.6" }
  ]
};
